
set(FILES
    Source/LDMChronoVehicleModuleInterface.cpp
    Source/LDMChronoVehicleModuleInterface.h
    Source/Clients/CockpitCameraComponent.cpp
    Source/Clients/CockpitCameraComponent.h
    Source/Clients/LDMChronoVehicleSystemComponent.cpp
    Source/Clients/LDMChronoVehicleSystemComponent.h
    Source/Clients/PoseSnapshots.cpp
    Source/Clients/PoseSnapshots.h
    Source/Clients/VehicleProxyComponent.cpp
    Source/Clients/VehicleProxyComponent.h
    Source/Simulation/ActiveVehicleRegistry.cpp
    Source/Simulation/ActiveVehicleRegistry.h
    Source/Simulation/ChassisPresentationConfig.h
    Source/Simulation/CoordinateConversion.cpp
    Source/Simulation/CoordinateConversion.h
    Source/Simulation/FixedStepClock.cpp
    Source/Simulation/FixedStepClock.h
    Source/Simulation/TerrainFixtureConfig.cpp
    Source/Simulation/TerrainFixtureConfig.h
    Source/Simulation/VehicleFixture.cpp
    Source/Simulation/VehicleFixture.h
)
